version: '3'
services:
  postgres-database:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      PGHOST: 'db'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: new-day-db
    volumes:
      - ./database:/var/lib/postgresql/data
